---
- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"

- include: "{{ item }}"
  with_first_found:
    - "install/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "install/{{ ansible_distribution }}.yml"
    - "install/{{ ansible_os_family }}.yml"

- name: Install Plex
  package: name={{ _plex_package_name }} state={{plex_state}}

- name: Ensure Plex is running
  service: name="{{ _plex_service_name }}" state="{{ plex_service_state }}"
